<?php

/**
 * This is the model base class for the table "{{student}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Student".
 *
 * Columns in table "{{student}}" available as properties of the model,
 * followed by relations of table "{{student}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $regno
 * @property integer $department
 * @property integer $level
 * @property integer $state
 * @property string $hometown
 * @property integer $profile
 *
 * @property Exeat[] $exeats
 * @property Department $department0
 * @property Level $level0
 * @property Profiles $profile0
 * @property State $state0
 */
abstract class BaseStudent extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{student}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Student|Students', $n);
	}

	public static function representingColumn() {
		return 'regno';
	}

	public function rules() {
		return array(
                        array('regno,profile', 'unique'),
			array('regno, department, level, state, profile', 'required'),
			array('department, level, state, profile', 'numerical', 'integerOnly'=>true),
			array('regno, hometown', 'length', 'max'=>45),
			array('hometown', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, regno, department, level, state, hometown, profile', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'exeats' => array(self::HAS_MANY, 'Exeat', 'student'),
			'department0' => array(self::BELONGS_TO, 'Department', 'department'),
			'level0' => array(self::BELONGS_TO, 'Level', 'level'),
			'profile0' => array(self::BELONGS_TO, 'Profiles', 'profile'),
			'state0' => array(self::BELONGS_TO, 'State', 'state'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'regno' => Yii::t('app', 'Regno'),
			'department' => null,
			'level' => null,
			'state' => null,
			'hometown' => Yii::t('app', 'Hometown'),
			'profile' => null,
			'exeats' => null,
			'department0' => null,
			'level0' => null,
			'profile0' => null,
			'state0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('regno', $this->regno, true);
		$criteria->compare('department', $this->department);
		$criteria->compare('level', $this->level);
		$criteria->compare('state', $this->state);
		$criteria->compare('hometown', $this->hometown, true);
		$criteria->compare('profile', $this->profile);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}