<?php

/**
 * This is the model base class for the table "{{status}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Status".
 *
 * Columns in table "{{status}}" available as properties of the model,
 * followed by relations of table "{{status}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $access_level
 *
 * @property Exeat[] $exeats
 */
abstract class BaseStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{status}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Status|Statuses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, access_level', 'required'),
			array('access_level', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>45),
			array('id, name, access_level', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'exeats' => array(self::HAS_MANY, 'Exeat', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'access_level' => Yii::t('app', 'Access Level'),
			'exeats' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('access_level', $this->access_level);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}