<?php

/**
 * This is the model base class for the table "{{users}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "{{users}}" available as properties of the model,
 * followed by relations of table "{{users}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $activkey
 * @property integer $userrole
 * @property string $create_at
 * @property string $lastvisit_at
 * @property integer $superuser
 * @property integer $status
 * @property string $createdby
 * @property string $modfiedby
 * @property string $modified
 *
 * @property Profiles $profiles
 * @property Userroles $userrole0
 */
abstract class BaseUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{users}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Users|Users', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('username, password, email, userrole, create_at', 'required'),
			array('userrole, superuser, status', 'numerical', 'integerOnly'=>true),
			array('username', 'length', 'max'=>20),
			array('password, email, activkey', 'length', 'max'=>128),
			array('lastvisit_at, createdby, modfiedby, modified', 'length', 'max'=>45),
			array('activkey, lastvisit_at, superuser, status, createdby, modfiedby, modified', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, email, activkey, userrole, create_at, lastvisit_at, superuser, status, createdby, modfiedby, modified', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'profiles' => array(self::HAS_ONE, 'Profiles', 'user_id'),
			'userrole0' => array(self::BELONGS_TO, 'Userroles', 'userrole'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'activkey' => Yii::t('app', 'Activkey'),
			'userrole' => null,
			'create_at' => Yii::t('app', 'Create At'),
			'lastvisit_at' => Yii::t('app', 'Lastvisit At'),
			'superuser' => Yii::t('app', 'Superuser'),
			'status' => Yii::t('app', 'Status'),
			'createdby' => Yii::t('app', 'Createdby'),
			'modfiedby' => Yii::t('app', 'Modfiedby'),
			'modified' => Yii::t('app', 'Modified'),
			'profiles' => null,
			'userrole0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('activkey', $this->activkey, true);
		$criteria->compare('userrole', $this->userrole);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('lastvisit_at', $this->lastvisit_at, true);
		$criteria->compare('superuser', $this->superuser);
		$criteria->compare('status', $this->status);
		$criteria->compare('createdby', $this->createdby, true);
		$criteria->compare('modfiedby', $this->modfiedby, true);
		$criteria->compare('modified', $this->modified, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}