<?php

/**
 * This is the model base class for the table "{{userroles}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Userroles".
 *
 * Columns in table "{{userroles}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $created
 * @property string $createdby
 * @property string $modified
 * @property string $modifiedby
 *
 */
abstract class BaseUserroles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{userroles}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User Type|User Types', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('description,name', 'required'),
			array('name, created, createdby, modified, modifiedby', 'length', 'max'=>45),
			array('name, created, createdby, modified, modifiedby', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, created, createdby, modified, modifiedby', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'created' => Yii::t('app', 'Created'),
			'createdby' => Yii::t('app', 'Createdby'),
			'modified' => Yii::t('app', 'Modified'),
			'modifiedby' => Yii::t('app', 'Modifiedby'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('createdby', $this->createdby, true);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('modifiedby', $this->modifiedby, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}