<?php

/**
 * This is the model base class for the table "{{setting}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Setting".
 *
 * Columns in table "{{setting}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $session
 * @property string $semester
 * @property string $semester_start_date
 * @property string $semester_end_date
 *
 */
abstract class BaseSetting extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{setting}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Setting|Settings', $n);
	}

	public static function representingColumn() {
		return 'session';
	}

	public function rules() {
		return array(
			array('session, semester, semester_start_date, semester_end_date', 'required'),
			array('session, semester, semester_start_date, semester_end_date', 'length', 'max'=>45),
			array('id, session, semester, semester_start_date, semester_end_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'session' => Yii::t('app', 'Session'),
			'semester' => Yii::t('app', 'Semester'),
			'semester_start_date' => Yii::t('app', 'Semester Start Date'),
			'semester_end_date' => Yii::t('app', 'Semester End Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('session', $this->session, true);
		$criteria->compare('semester', $this->semester, true);
		$criteria->compare('semester_start_date', $this->semester_start_date, true);
		$criteria->compare('semester_end_date', $this->semester_end_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}